### ISSUE TITLE
[Document] 컴포넌트 정의서 템플릿

### ISSUE THREAD

**Issue by thiporia** [linewalks/MDwalks-UI#904]
## 기능에 관한 설명 또는 링크
OKR인 컴포넌트 정의서 템플릿 구상

## 선행 이슈 링크
없습니다.

## 원하는 솔루션에 대한 설명
컴포넌트 정의서 템플릿을 작성합니다.

## 요구 조건
- [ ] 해당 컴포넌트의 구조를 설명할 수 있어야 한다.
- [x] 해당 컴포넌트의 기능을 설명할 수 있어야 한다.

## 테스트 항목
- 문서 작업으로 테스트는 없습니다.

## 완료 후 진행
작업 완료 후 Markdown 또는 텍스트 파일로 정의서 템플릿 업로드 합니다.

**Comment by thiporia** [comment]
- 검토할 것 [markserv](https://github.com/markserv/markserv)

**Comment by thiporia** [comment]
markserv 실행시 에러 발생
```
$ markserv ./
  Markserv   boot: starting Markserv...
  Markserv   address: http://localhost:8642
  Markserv   path: /Users/sseon/Workspace/MDwalks-UI
  Markserv   livereload: communicating on port: 35729
  Markserv   process: your pid is: 66379
  Markserv   stop: press [Ctrl + C] or type "sudo kill -9 66379"
    GitHub   Contribute on Github - github.com/markserv
  Markserv   upgrade: checking for upgrade...
  Markserv   dir: /Users/sseon/Workspace/MDwalks-UI/
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/Users/sseon/Workspace/MDwalks-UI/node_modules/chokidar/index.js:260:10)
    at /Users/sseon/Workspace/MDwalks-UI/node_modules/chokidar/lib/nodefs-handler.js:55:5
    at Array.forEach (<anonymous>)
    at fsWatchBroadcast (/Users/sseon/Workspace/MDwalks-UI/node_modules/chokidar/lib/nodefs-handler.js:54:36)
    at FSWatcher.<anonymous> (/Users/sseon/Workspace/MDwalks-UI/node_modules/chokidar/lib/nodefs-handler.js:100:9)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:133:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
error Command failed with exit code 1.
```
